import '@fortawesome/fontawesome-free/css/all.min.css'
import type { NextPage } from 'next'
import Head from 'next/head'
import { NavItem } from '~/components/Navbar'
import Header from '~/components/Header'

const Home: NextPage = () => {
   const items: NavItem[] = [
      { path: '/products/asus', title: 'Asus' },
      { path: '/products/lenovo', title: 'Lenovo' },
      { path: '/products/mac', title: 'Mac' },
   ]

   return (
      <div className='container flex justify-center'>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <Header />
      </div>
   )
}

export default Home
