@host = localhost
@port = 80
@baseUrl = http://{{host}}:{{port}}
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiaWF0IjoxNjMzNjI3MTk2fQ.aW6qy49yJvStlQ3k230dqyPcbqQKNrz9BJR0vMTGCK8
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiQWRtaW4iLCJnZW5kZXIiOiJNQUxFIiwiaWQiOiIxOGIwMDMwZC0xNzFjLTRlY2UtYjlkYi04YmZlNjI2YzRjNGYiLCJwaG9uZSI6Iis4NDEyMzQ1Njc4OSIsImlhdCI6MTY0MDAyMjAxNX0.FaSBPf_Yc8Gjfllesds2-Rud77p9zTyTe_5ywQLtJqk
############################################################
@username = "admin@gmail.com"
@password = "123456"

POST {{baseUrl}}/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($username: String!, $password: String!) {
   logIn(username: $username, password: $password) {
      action
      isSuccess
      data
      message
      errors
   }
}

{
   "username": {{username}},
   "password": {{password}}
}

############################################################
<@file ./tester.rest

POST {{baseUrl}}/graphql HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($data: ImageCreateInput!) {
   logIn(data: $data, file: {{@file}}) {
      action
      isSuccess
      data
      message
      errors
   }
}

{
   "data": {
      "title": "file"
   }
}

############################################################
POST {{baseUrl}}/graphql HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  findManyLaptop {
    price
    rating
  }
}