export enum Action {
   AGGREGATE = 'AGGREGATE',
   COUNT = 'COUNT',
   CREATE = 'CREATE',
   CREATE_MANY = 'CREATE_MANY',
   DELETE = 'DELETE',
   DELETE_MANY = 'DELETE_MANY',
   FIND_FIRST = 'FIND_FIRST',
   FIND_MANY = 'FIND_MANY',
   FIND_UNIQUE = 'FIND_UNIQUE',
   GROUP_BY = 'GROUP_BY',
   UPDATE = 'UPDATE',
   UPDATE_MANY = 'UPDATE_MANY',
}
